apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-deployment
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: result-deployment
    spec:
      containers:
      - image: ziyaasici/phonebook-resultserver:v1
        name: phonebook-resultserver
        ports:
        - containerPort: 80
        resources: {}
        envFrom:
          - configMapRef:
              name: server-config
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: mysql-secret
status: {}
