apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-service
  name: result-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  selector:
    app: result-deployment
  type: NodePort
status:
  loadBalancer: {}
