apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-service
  name: web-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: web-deployment
  type: NodePort
status:
  loadBalancer: {}
