apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-deployment
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: result-deployment
    spec:
      containers:
      - image: ziyaasici/phonebook-resultserver:v1
        name: phonebook-resultserver
        ports:
        - containerPort: 80
        resources: {}
status: {}
