apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-deployment
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
      - image: ziyaasici/phonebook-webserver:v1
        name: phonebook-webserver
        ports:
        - containerPort: 80
        resources: {}
status: {}
